# .github/workflows/build-release.yml

name: 'Build & Release'
on:
  push:
    tags:
      - 'v*' # Run this workflow when you create a git tag like v1.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest] # We can build the Linux packages on an Ubuntu runner

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build the application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # Uses the git tag for the release name
          releaseName: 'App v__VERSION__' # The name of the release. __VERSION__ will be replaced by the tag.
          releaseBody: 'See the assets to download this version.'
          releaseDraft: true
          prerelease: false
